name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  install-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Clean Yarn cache
        run: yarn cache clean

      - name: Increase memory limit
        run: export NODE_OPTIONS=--max_old_space_size=4096

      - name: Install dependencies
        run: yarn install

      - name: Upload node_modules
        uses: actions/upload-artifact@v4
        with:
          name: node-modules
          path: node_modules/

  build-and-test:
    runs-on: ubuntu-latest
    needs: install-dependencies

    strategy:
      matrix:
        project:
          - core
          - ui-react

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download node_modules
        uses: actions/download-artifact@v4
        with:
          name: node-modules
          path: node_modules/

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
  
      - name: Install dependencies
        run: yarn install

      - name: Lint ${{ matrix.project }}
        run: npx nx run ${{ matrix.project }}:lint
      
      - name: Test ${{ matrix.project }}
        run: npx nx run ${{ matrix.project }}:test --coverage --coverageReporters=lcov
      
      - name: Build ${{ matrix.project }}
        run: npx nx run ${{ matrix.project }}:build

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: coverage/

  sonarqube:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Clean Yarn cache
        run: yarn cache clean

      - name: Install dependencies
        run: yarn install

      # - name: Download node_modules
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: node-modules
      #     path: node_modules/

      - name: Download coverage reports
        uses: actions/download-artifact@v4
        with:
          name: coverage-reports
          path: coverage/

      - name: Merge coverage reports
        run: node coverageMerger.js

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}