name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project:
          - core
          - ui-react

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install

      - name: Lint ${{ matrix.project }}
        run: yarn nx run ${{ matrix.project }}:lint
      
      - name: Test ${{ matrix.project }}
        run: yarn nx run ${{ matrix.project }}:test
      
      - name: Build ${{ matrix.project }}
        run: yarn nx run ${{ matrix.project }}:build

      