name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  install-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          cache: 'npm'

      - name: Increase memory limit
        run: export NODE_OPTIONS=--max_old_space_size=4096

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # - name: Upload node_modules
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: node-modules
      #     path: node_modules/

  build-and-test:
    runs-on: ubuntu-latest
    needs: install-dependencies

    strategy:
      matrix:
        project:
          - core
          - ui-react

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          cache: 'npm'

      - name: Lint ${{ matrix.project }}
        run: npx nx run ${{ matrix.project }}:lint
      
      - name: Test ${{ matrix.project }}
        run: npx nx run ${{ matrix.project }}:test --coverage --coverageReporters=lcov
      
      - name: Build ${{ matrix.project }}
        run: npx nx run ${{ matrix.project }}:build

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: coverage/

  sonarqube:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          cache: 'npm'

      # - name: Download node_modules
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: node-modules
      #     path: node_modules/

      - name: Download coverage reports
        uses: actions/download-artifact@v4
        with:
          name: coverage-reports
          path: coverage/

      - name: Merge coverage reports
        run: node coverageMerger.js

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}